name: Java CI
on:
    push:
        tags-ignore:
            - "*"
    pull_request:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up JDK 1.8
                uses: actions/setup-java@v1
                with:
                    java-version: 1.8
            -   run: .github/build.sh
                env:
                    GH_EVENT_NAME: ${{ github.event_name }}
                    # push, pull_request
                    GH_REF: ${{ github.ref }}
