name: Java CI
on:
    push:
        branches:
            - '**'
        tags-ignore:
            - '*'
    pull_request:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up JDK 1.8
                uses: actions/setup-java@v1
                with:
                    java-version: 1.8
            -   run: .github/workflows/build.sh
                env:
                    GH_EVENT_NAME: ${{ github.event_name }}
                    GH_REF: ${{ github.ref }}
            -   uses: actions/create-release@v1
                if: ${{ $TAG }}
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    tag_name: ${{ $TAG }}
                    release_name: Release ${{ $TAG }}
