name: Master/Pull-Request CI
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            -   master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up JDK 1.8
                uses: actions/setup-java@v1
                with:
                    java-version: 1.8
            -   run: |
                    set -eu
                    version=$(docker run -i denisa/clq -release -query 'releases[0].version' < CHANGELOG.md)
                    tag="${version}"
                    if git ls-remote -q --tags | grep -q "${tag}$"; then
                        # shellcheck disable=SC2154
                        echo "🚫 Tag ${tag} already exists for version ${version}"
                        echo "   Update from master and update the CHANGELOG.md"
                        exit 1
                    fi
                    echo "✅ version ${version} hasn't been used yet"

                    mvn --no-transfer-progress -B -P ci -Drevision="${version}" -PreleaseValidation deploy
